"""Update foreign key columns to UUID

Revision ID: 54066ba1759f
Revises: ab2504c7de8b
Create Date: 2024-11-18 23:17:48.196644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54066ba1759f'
down_revision: Union[str, None] = 'ab2504c7de8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
