name: ai-fashion-ci=cd

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ai-fashion-bck
    steps:
    
    - name: Server Update
      run: sudo apt update -y

    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Compose Down
      run: docker compose down

    - name: Docker Build
      env:
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: docker compose build

    - name: Docker Up
      run: docker compose up

    - name: Docker Clean Up
      run: docker system prune -af
